### ISSUE TITLE
This gem doesn't work on Ruby 3.1 due to a breaking change of `YAML#load`

### ISSUE THREAD

**Issue by tomgi** [krisleech/wisper-sidekiq#34]
Ruby 3.1 comes with Psych 4.0 bundled, which changes `YAML#load` to behave like `YAML#safe_load` (instead of `YAML#unsafe_load`). See https://github.com/ruby/psych/pull/487 for more details.

This results in `Psych::DisallowedClass: Tried to load unspecified class:` for all registered async subscriber classes.

**Comment by alexisraca** [comment]
gem looks abandoned

**Comment by moiristo** [comment]
@krisleech this is also preventing us from upgrading to ruby 3. Could you please merge it in or let us know if we need to create a `swanky-wisper-sidekiq` gem instead?

**Comment by alexdunae** [comment]
One partial fix for this is to pass a string into `Wisper.subscribe` instead of a class or module.  That way `YAML.load` won't need to deserialize the class/module in order to run your Sidekiq job.

```ruby
# instead of this
Wisper.subscribe(AsyncActivityLogger, async: true)

# do this
Wisper.subscribe("AsyncActivityLogger", async: true)
```

This won't help if your payload includes other data types that aren't allowed via `YAML.safe_load` but it did fix most of the errors while I was upgrading our application.

Longer term, I wonder if a more ideal solution would be to allow passing in permitted_classes via something like this:

```ruby 
Wisper.configure do |config|
  config.yaml_permitted_classes = ["DateTime", "AsyncActivityLogger"]
end
```

**Comment by patrickemuller** [comment]
@krisleech Do we have a schedule or at least a timeline for this? Don't want to rush, but Ruby 3 is kinda awesome and we want to use in our app too

**Comment by moiristo** [comment]
Forked to https://github.com/bookingexperts/wisper-sidekiq and applied Sean's patch there for now.

**Comment by tomgi** [comment]
I opened a pull request with an alternative solution that uses `::YAML.safe_load` by default, and requires custom types to be explicitly registered if used as event arguments https://github.com/krisleech/wisper-sidekiq/pull/36

**Comment by alessandrostein** [comment]
> Forked to https://github.com/bookingexperts/wisper-sidekiq and applied Sean's patch there for now.

This fork is not available anymore?

**Comment by moiristo** [comment]
@alessandrostein The change is in master, so you can just use this repo now instead of the fork.
