### ISSUE TITLE
[Rspec] wisper can't execute the sidekiq

### ISSUE THREAD

**Issue by frankgu** [krisleech/wisper-sidekiq#6]
Dear @krisleech,

When I was using 'Sidekiq' for 'Wisper' and I want to test my function using Rspec, it seemed that wisper couldn't start a sidekiq job.

In my <b>Request.rb</b> file, I've got:
```Ruby
after_commit :publish_creation, on: :create
```
and
```Ruby
def publish_creation
	broadcast(:publish_request_creation, self.id)
end
```

In my <b> requestlistener </b> file, I've got:
```Ruby
def self.publish_request_creation(request_id)
      request = Core::Request.find_by_id(request_id)
      request.tutor.change_state('matching')
      request.student.change_state('matching')
      p PREFIX + "updating student:#{request.student.id} and tutor:#{request.tutor.id} states"
end
```

Then, in my test file, I've got:
```Ruby
post api_v1_students_request_look_for_prioritized_tutor_path, 
    	 { subject: xxx },
    	 { "AUTHORIZATION" => xxx}
      expect(response).to be_success
      expect { Listener::Requestlistener }.to broadcast(:publish_request_creation)
```

I will create a <b>request</b> when I post to <code>api_v1_students_request_look_for_prioritized_tutor_path</code>. However, sidekiq is not running at all, and I will get the error message 
```
Failure/Error: expect { Listener::Requestlistener }.to broadcast(:publish_request_creation)
       expected publisher to broadcast publish_request_creation event
```
I will be very appreciated if you can help me with this problem! Thank you in advance.

**Comment by krisleech** [comment]
You are expecting the `Listener::Requestlistener` class to broadcast the event. But it is not the listener that broadcasts, it receives an event.

Looking at your code it appears an instance of `Request` is the publisher. So it needs to be more like `expect { request }.to broadcast(...)`. Also note that Sidekiq does not need to be running when using the `broadcast` matcher since internally it subscribes its own listener to the given publisher synchronously.

If you want to check the listener receives an event then you could do something like `expect { Listener::Requestlistener }.to receive(:publish_request_creation)`.
